version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - '${MYSQL_PORT}:3306'
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql
  test-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_TEST}
      MYSQL_DATABASE: ${MYSQL_DATABASE_TEST}
      MYSQL_USER: ${MYSQL_USER_TEST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_TEST}
      MYSQL_PORT: ${MYSQL_PORT_TEST}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    ports:
      - '${MYSQL_PORT_TEST}:3306'
    networks:
      - mynetwork2
    volumes:
      - mysql_test_data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
  mynetwork2:
    driver: bridge
volumes:
  mysql_data:
  mysql_test_data:
